name: CI
on:
  workflow_dispatch:
    inputs:
      branch:
        description: Branch name to re-build ?
        required: true
        type: string
  push:
  pull_request:
    branches:
      - 'main'
jobs:
  build:
    env:
      branch: ${{ inputs.branch || github.head_ref || github.ref_name }}
      ELECTRON_EXTRA_LAUNCH_ARGS: '--disable-gpu'

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.branch }}
          token: ${{secrets.DONTCODE_ACTIONS_TOKEN}}
          fetch-depth: 2
      - name: Git config user
        uses: snow-actions/git-config-user@v1.0.0
        with:
          name: Dont-code
          email: developer@dont-code.net
      - uses: actions/setup-node@v4
        with:
          node-version: 20
#      - name: Verify Change Logs
#        run: node common/scripts/install-run-rush.js change --verify
      - name: Rush Install
        run: node common/scripts/install-run-rush.js install
      - name: Rush rebuild
        run: node common/scripts/install-run-rush.js rebuild
      - name: Unit Tests
        run: node common/scripts/install-run-rush.js test
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
         name: test-logs
         path: ./*/*/*.test*.log
