name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v4
        with:
          node-version: 20
#      - name: Verify Change Logs
#        run: node common/scripts/install-run-rush.js change --verify
      - name: Rush Install
        run: node common/scripts/install-run-rush.js install
      - name: Rush rebuild
        run: node common/scripts/install-run-rush.js rebuild
      - name: Unit Tests
        run: node common/scripts/install-run-rush.js test
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
         name: test-logs
         path: ./*/*/*.test*.log
