name: Website update from Readme
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - '**/README.md'
      - 'docs/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.branch }}
          token: ${{secrets.DONTCODE_ACTIONS_TOKEN}}
          fetch-depth: 1
      - name: Git config user
        uses: snow-actions/git-config-user@v1.0.0
        with:
          name: Ng-xtend
          email: developer@dont-code.net
      - name: Update Ng-xtend.dev website from Readme
        uses: wlixcc/SFTP-Deploy-Action@v1.2.6
        with:
          username: ${{secrets.NG_XTEND_DEV_WEBSITE_USER}}
          password: ${{secrets.NG_XTEND_DEV_WEBSITE_PASSWORD}}
          local_path: './docs/ng-xtend-website/*'
          remote_path: '/www'
          server: 'ng-xtend.dev'
          port: ${{secrets.DONTCODE_WEBSITE_SSH_PORT}}
          sftp_only: 'true'
          delete_remote_files: 'false'
